[build]
  publish = "dist/public"
  command = "vite build && cp _redirects dist/public/_redirects"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/cart"
  to = "/.netlify/functions/cart"
  status = 200

[[redirects]]
  from = "/api/cart/*"
  to = "/.netlify/functions/cart"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/cep/*"
  to = "/.netlify/functions/cep"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"